name: telepatia_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.7.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  record: ^5.2.0
  path_provider: ^2.1.5
  firebase_core: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4
  flutter_gen_runner: ^5.9.0

flutter:
  uses-material-design: true
  generate: true
