// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkpiT_kxUbbJQPcoHpYaCUAZa7PQ6yTmg',
    appId: '1:36018067940:web:6c7e65fd5f814513c1cff1',
    messagingSenderId: '36018067940',
    projectId: 'stealth-comerce',
    authDomain: 'stealth-comerce.firebaseapp.com',
    databaseURL: 'https://stealth-comerce-default-rtdb.firebaseio.com',
    storageBucket: 'stealth-comerce.firebasestorage.app',
    measurementId: 'G-RDC06WEQBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4vLQXp_BKjUDGRtxsYb6VJ5xyVdwLF7o',
    appId: '1:36018067940:android:964e5a5f72b025dec1cff1',
    messagingSenderId: '36018067940',
    projectId: 'stealth-comerce',
    databaseURL: 'https://stealth-comerce-default-rtdb.firebaseio.com',
    storageBucket: 'stealth-comerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5LXuRfiJKntpFpJ02-3Pb6wyh9tXRCno',
    appId: '1:36018067940:ios:00a51d12f9bda000c1cff1',
    messagingSenderId: '36018067940',
    projectId: 'stealth-comerce',
    databaseURL: 'https://stealth-comerce-default-rtdb.firebaseio.com',
    storageBucket: 'stealth-comerce.firebasestorage.app',
    iosBundleId: 'com.camackley.telepatiaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5LXuRfiJKntpFpJ02-3Pb6wyh9tXRCno',
    appId: '1:36018067940:ios:00a51d12f9bda000c1cff1',
    messagingSenderId: '36018067940',
    projectId: 'stealth-comerce',
    databaseURL: 'https://stealth-comerce-default-rtdb.firebaseio.com',
    storageBucket: 'stealth-comerce.firebasestorage.app',
    iosBundleId: 'com.camackley.telepatiaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkpiT_kxUbbJQPcoHpYaCUAZa7PQ6yTmg',
    appId: '1:36018067940:web:4c245fd4bcccf6c5c1cff1',
    messagingSenderId: '36018067940',
    projectId: 'stealth-comerce',
    authDomain: 'stealth-comerce.firebaseapp.com',
    databaseURL: 'https://stealth-comerce-default-rtdb.firebaseio.com',
    storageBucket: 'stealth-comerce.firebasestorage.app',
    measurementId: 'G-SBVVNG3DH8',
  );
}
